name: Publish Extension

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    defaults:
      run:
        working-directory: ext/vscode-extension

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ext/vscode-extension/package-lock.json
          cache-dependency-path: ext/vscode-extension/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Package extension
        run: npm run package

      - name: Publish to Open VSX Registry (Cursor)
        run: npx ovsx publish stylecast-*.vsix -p ${{ secrets.OVSX_PAT }}
        continue-on-error: true

      - name: Publish to VS Code Marketplace
        run: npx vsce publish --packagePath stylecast-*.vsix -p ${{ secrets.VSCE_PAT }}
        continue-on-error: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: stylecast-*.vsix
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
