name: Publish Extension

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ext/vscode-extension

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Publish to Open VSX Registry (Cursor)
        uses: HaaLeo/publish-vscode-extension@v1
        id: publish-ovsx
        with:
          pat: ${{ secrets.OVSX_PAT }}
          packagePath: ext/vscode-extension
        continue-on-error: true

      - name: Publish to VS Code Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        id: publish-vsce
        with:
          pat: ${{ secrets.VSCE_PAT }}
          registryUrl: https://marketplace.visualstudio.com
          packagePath: ext/vscode-extension
        continue-on-error: true

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.publish-vsce.outputs.vsixPath }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
